export type Company = {
  id: string
  name: string
  industry: string
  location: string
  stage: string
  website: string
  description: string
  founded: number
}

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Stripe",
    industry: "Fintech",
    location: "San Francisco",
    stage: "Series I",
    website: "https://stripe.com",
    description: "Financial infrastructure platform for the internet. Millions of companies use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.",
    founded: 2010,
  },
  {
    id: "2",
    name: "Notion",
    industry: "Productivity",
    location: "San Francisco",
    stage: "Series C",
    website: "https://www.notion.so",
    description: "All-in-one workspace for notes, tasks, wikis, and databases. Notion blends everyday work tools into one.",
    founded: 2013,
  },
  {
    id: "3",
    name: "Vercel",
    industry: "Developer Tools",
    location: "San Francisco",
    stage: "Series D",
    website: "https://vercel.com",
    description: "Frontend cloud platform enabling developers to build and deploy web experiences. Creators of Next.js.",
    founded: 2015,
  },
  {
    id: "4",
    name: "Plaid",
    industry: "Fintech",
    location: "San Francisco",
    stage: "Series D",
    website: "https://plaid.com",
    description: "Data network powering the fintech tools millions of people rely on to live a healthier financial life.",
    founded: 2013,
  },
  {
    id: "5",
    name: "Supabase",
    industry: "Developer Tools",
    location: "Singapore",
    stage: "Series C",
    website: "https://supabase.com",
    description: "Open source Firebase alternative providing database, authentication, instant APIs, edge functions, and realtime subscriptions.",
    founded: 2020,
  },
  {
    id: "6",
    name: "Linear",
    industry: "Productivity",
    location: "San Francisco",
    stage: "Series B",
    website: "https://linear.app",
    description: "Streamlined issue tracking and project management tool built for high-performance software teams.",
    founded: 2019,
  },
  {
    id: "7",
    name: "Prisma",
    industry: "Developer Tools",
    location: "Berlin",
    stage: "Series B",
    website: "https://www.prisma.io",
    description: "Next-generation ORM for Node.js and TypeScript. Makes database access easy with type-safe queries.",
    founded: 2016,
  },
  {
    id: "8",
    name: "Ramp",
    industry: "Fintech",
    location: "New York",
    stage: "Series D",
    website: "https://ramp.com",
    description: "Corporate card and spend management platform that helps companies save time and money with automated expense management.",
    founded: 2019,
  },
  {
    id: "9",
    name: "Loom",
    industry: "Productivity",
    location: "San Francisco",
    stage: "Series C",
    website: "https://www.loom.com",
    description: "Video messaging platform for work. Record quick videos of your screen and cam to communicate with your team.",
    founded: 2015,
  },
  {
    id: "10",
    name: "Deno",
    industry: "Developer Tools",
    location: "New York",
    stage: "Series A",
    website: "https://deno.com",
    description: "Modern runtime for JavaScript and TypeScript with a cloud-native hosting platform called Deno Deploy.",
    founded: 2018,
  },
  {
    id: "11",
    name: "Mercury",
    industry: "Fintech",
    location: "San Francisco",
    stage: "Series C",
    website: "https://mercury.com",
    description: "Banking for startups. Mercury offers checking, savings, treasury, credit cards, and venture debt for companies at every stage.",
    founded: 2017,
  },
  {
    id: "12",
    name: "Coda",
    industry: "Productivity",
    location: "Mountain View",
    stage: "Series D",
    website: "https://coda.io",
    description: "All-in-one document platform that blends the flexibility of docs, structure of spreadsheets, and power of applications.",
    founded: 2014,
  },
  {
    id: "13",
    name: "Railway",
    industry: "Developer Tools",
    location: "San Francisco",
    stage: "Series A",
    website: "https://railway.app",
    description: "Infrastructure platform where you can deploy any app, database, or service. Instant deployments with zero DevOps.",
    founded: 2020,
  },
  {
    id: "14",
    name: "Brex",
    industry: "Fintech",
    location: "San Francisco",
    stage: "Series D",
    website: "https://www.brex.com",
    description: "AI-powered spend platform that helps companies make better financial decisions with corporate cards, expense management, and travel.",
    founded: 2017,
  },
  {
    id: "15",
    name: "Miro",
    industry: "Productivity",
    location: "San Francisco",
    stage: "Series C",
    website: "https://miro.com",
    description: "Visual collaboration platform that helps teams ideate, create, and collaborate using an online whiteboard.",
    founded: 2011,
  },
]